services:
  - type: web
    name: n8n-discord-bot
    env: node
    region: oregon # Free tier available
    plan: free # Free tier - 750 hours/month
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: UTC
      - key: PORT
        value: 10000
      - key: SPOTLIGHT_ENABLED
        value: true
      - key: LOG_LEVEL
        value: info
      - key: DISCORD_TOKEN
        sync: false # Set manually in Render dashboard
    autoDeploy: true
    preDeployCommand: echo "Starting n8n Discord Bot deployment..."
